const Colors = {
  light: {
    primary: '#4A7BF7',
    primaryLight: '#6B92FF',
    primaryDark: '#3A6AE0',
    secondary: '#9D7BFF',
    secondaryLight: '#B292FF',
    secondaryDark: '#8A6AE0',
    accent: '#4ECDC4',
    accentLight: '#6FDED6',
    accentDark: '#3BBCB3',
    protein: '#9D7BFF',
    fruits: '#7ED957',
    steps: '#5BBFEA',
    water: '#5BBFEA',
    background: '#FFFFFF',
    backgroundSecondary: '#F8F9FA',
    card: '#FFFFFF',
    text: '#333333',
    textSecondary: '#666666',
    textTertiary: '#999999',
    border: '#E5E5E5',
    error: '#FF6B6B',
    success: '#4ECDC4',
    warning: '#FFD166',
    info: '#5BBFEA',
    shadow: 'rgba(0, 0, 0, 0.1)',
    overlay: 'rgba(0, 0, 0, 0.5)',
    transparent: 'transparent',
  },
  dark: {
    primary: '#4A7BF7',
    primaryLight: '#6B92FF',
    primaryDark: '#3A6AE0',
    secondary: '#9D7BFF',
    secondaryLight: '#B292FF',
    secondaryDark: '#8A6AE0',
    accent: '#4ECDC4',
    accentLight: '#6FDED6',
    accentDark: '#3BBCB3',
    protein: '#9D7BFF',
    fruits: '#7ED957',
    steps: '#5BBFEA',
    water: '#5BBFEA',
    background: '#121212',
    backgroundSecondary: '#1E1E1E',
    card: '#242424',
    text: '#FFFFFF',
    textSecondary: '#AAAAAA',
    textTertiary: '#888888',
    border: '#333333',
    error: '#FF6B6B',
    success: '#4ECDC4',
    warning: '#FFD166',
    info: '#5BBFEA',
    shadow: 'rgba(0, 0, 0, 0.3)',
    overlay: 'rgba(0, 0, 0, 0.7)',
    transparent: 'transparent',
  },
  // For backward compatibility
  primary: '#4A7BF7',
  primaryLight: '#6B92FF',
  primaryDark: '#3A6AE0',
  secondary: '#9D7BFF',
  secondaryLight: '#B292FF',
  secondaryDark: '#8A6AE0',
  accent: '#4ECDC4',
  accentLight: '#6FDED6',
  accentDark: '#3BBCB3',
  protein: '#9D7BFF',
  fruits: '#7ED957',
  steps: '#5BBFEA',
  water: '#5BBFEA',
  background: '#FFFFFF',
  backgroundSecondary: '#F8F9FA',
  card: '#FFFFFF',
  text: '#333333',
  textSecondary: '#666666',
  textTertiary: '#999999',
  border: '#E5E5E5',
  error: '#FF6B6B',
  success: '#4ECDC4',
  warning: '#FFD166',
  info: '#5BBFEA',
  shadow: 'rgba(0, 0, 0, 0.1)',
  overlay: 'rgba(0, 0, 0, 0.5)',
  transparent: 'transparent',
};

export default Colors;